### ISSUE TITLE
запилить тесты

### ISSUE THREAD

**Issue by ctrlok** [DMiTRONiK/DevOps-experience#11]
надо сделать так что бы #10 показывал ошибку и не мог задеплоиться на прод

**Comment by DMiTRONiK** [comment]
1. Добавить линтер/валидатор для других типов файлов, в настройках репозитория запретить мерж без прохождения проверки.
2.  Написать тест проверяющий ответ веб-сервера после сборки образа
3. еще не придумал ...

**Comment by ctrlok** [comment]
хорошие варианты. Давай их сделаем.
