### ISSUE TITLE
изменения по PR 

### ISSUE THREAD

**Issue by ctrlok** [DMiTRONiK/DevOps-experience#12]
1. А при чём тут `PWD` к compose-production? зачем нужна эта переменная? 
2. остановится ли выполнения скрипта? Нужно ли продолжать выполнение?

_Originally posted by @ctrlok in https://github.com/DMiTRONiK/DevOps-experience/pull/8#discussion_r863545070_

**Comment by DMiTRONiK** [comment]
https://github.com/DMiTRONiK/DevOps-experience/pull/8#discussion_r863571965
