### ISSUE TITLE
создать GitHub actions

### ISSUE THREAD

**Issue by ctrlok** [DMiTRONiK/DevOps-experience#3]
Создать github actions для того чтобы собирать контекнеры и пушить их в репозиторий по коммиту в мастер
Также создать другой compose.production.yaml для того чтобы запускать используя уже запушенные репы

**Comment by DMiTRONiK** [comment]
> пушить их в репозиторий

В какой репозиторий?

**Comment by DMiTRONiK** [comment]
Создал [action  ](https://github.com/DMiTRONiK/DevOps-experience/blob/main/.github/workflows/docker-image.yml)который пушит образ в docker-hub

**Comment by ctrlok** [comment]
сделал задачу ↑↑↑

**Comment by ctrlok** [comment]
ещё необходим docker-compose.production как в описании
